language: android

jdk:
  - oraclejdk8

android:
  components:
    # Use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    - build-tools-25.0.0
    - android-25

    # Additional components
    - extra-android-m2repository
    - extra-android-support

  licenses:
    - 'android-sdk-license.*'

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

before_script:
  - chmod +x gradlew      # Grand permissions

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - ./gradlew build jacocoTestReport

after_success:
  - scripts/publishToBintray.sh
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
  global:
    - secure: "BsopIH+ofke0mmIXTflknhM8PExE2pKrwynxiS6twsDe9mIj9/9Xrkz/jFHYlaNZhg4f60+Z3A8ptpWp6pPYP8mycBW+4ZEjPt8y7Eu9lRDTAMzvkIt8uXbwXdNZLoFp37XNKjt8hmSRaWYx+g0Cji+Z523ZPGrelDCKgrr+oUEDuTQ33AjUpFKbsHn3Kl4L31r1D8lH9+27V9K9z+f2S68KCT0gX+FNTy4/8iUm3T3bBWwbuU7EvrqbL41I4mpnlVWajZaSBtnpOrqGxF91pu6EeejmoCmGFCa00/OQqBJ+9nHEZgHogl9KFJXBtUKlxcNfPiBwWVTBhkLAu/+P/1LkqO+rkzYzZG7WzrZ+wJS6kbyVBOAdi2o3PvO0DD2h3/gUMBV7iQ18x8GK2+lV7Rwc3iGUwex+BgXfi8stXYDcl/LXkkZ9FXDqGopTMazgBfzpJbqbtVLRzF9CROVKcPvx2fDQZxe3VEjoXSJcrFGB3eVkWeetDYRDcSHqcyJqruUoxIowuMubiNQ3grSDOFN2qp8EwiDJMhIIBdo8yOPkhejC29W1n12Zydb4jUaU0+IxH9ATHCzfqvi8GuU23h4xOKxodnUL7dhY0bpSDGqYdYoecK0rs+zShYcBRT5luS/4l+K0gUISPnFgkaKG935OYthGuTJdzJBLYfiKknM="
    - secure: "NOQvoweIBOF1AgME/uGjq2fTXyTSPGKGtIhkEcZD+AbJeWoanH8BUJ564/lAbErS4Hy9+Kpmy6f0q7K6/s2hq9MzbOOzsbmDnaEpAmEr8i+GWI2BsMH8aYTG9vk3YbqzoR1QcQDWz60q6CFwq3VuX957sgJpTsyh5lrBVsYrzc7lKrCIAib5aB88C2S33keSycQFl8/AptQnkIREhtcmgXSfeoVBTEY9Wwp+dKZW6KB2vtF2KYirdHFtQdTF6dttztXqnPYqI23WeYahL9h5TFomDW5/ku2hL8nuxtgqvHj6SBCcdYl5PgxahuVbnPIpDuwkLqwAQRFMKtjikpVTYsR5ecgYhHA75wRchGd86wargRobGk6IVHM1LWRc4P7ig6W4qwod8gqasHu6pOlQggWcZS0y+S5LV7RGH4nS1uxjfq934GdlrC0VAyzdhufmqRPGHA31NF6xstGUNS0EuMjMaM4l6b7/CuxpXRlL24AI6UKSf60wuu5wq58N4WW3UfEOQuAyRuXaVyWxQEWEjIRWUmvxzELb6pSUtrFyLPEuRFVRtAZVcQdqY/bfoKM1+NfCV4tbEYjOztwyINugTTf5iobmLFaGswxFLOE07qOf+N/AIdF9JsGcsquo4rWmjfMkb7byuf7B3obrLkiMpm6CQ2b9bz1drf79TrUld80="
    - secure: "BJJFtDOts3l+KZhI41EgW7BxlAQUrYRrKSuSRWqyuSCVVyTFmC6VRrGrq/sQWMKBW6L4qEJuJuOTvHmUE41H3iavEo4NcGmfU8yDoKsjtkSQfT9/GaLxR2BwsMFVZfUxr/R/X/uF8Nu7sW46n6zhGLFnKAPB5d1F6w/rfyiPzF5SxT/7yhE7cz+qOe9rmQySH+8uhy3nLAWNTE/40au+7Qaaog61ys//TU20WxqJHgLV5fI9FWF10rQaAKsqqheOn6k8olxF7sAza0fpp0nuLTVm/91LpDq1q6SiuK2WX6XtMH6zpTICOR+lZLZifkZV31/3jVoZ++5ywzbnp5lz/QFQkqmDRzAO7RaZpgDHXo3p5eCoX4y3smOcDsfr6KfrsIOPKHcNcuLFU1herv8DvfLnGPtGdwik8NerbxMKabQ+OcQE97wnrUN2HM6CQPNH5vq8YyjtW3WBzy+G/tovH4tJv7hlCIXi2ynSUKLaKvJU/sGPfJxS0PHPsVA67DN6cKicO2/o7jpUTgb17wUDsDCSnc6/zXE552wmGoGu4SKi9FKNVwX16v0GSqIuyLKYgir3xU/NPPdOPwTlVoXhKA5I5sJLL4Ub431uBtnW88+A07m5YQgmnc57W+cazt4muMRNetlDxz1P2aPMUYTOMouku/JiVvZKWrwaJiUJ3Vc="
    - secure: "H7VAy5+1Dna+VGjggpgR7ICOfhl6DVefDXwcwhRfEbLk5dH8woD04ejU2MwEzc7INqj8zJz55wPZxwvqTTZAlOAx8w+Ih+q8N6AAcVGKwVdqzbCQPDSm3AQtb5vZCvXM8dG9GP4AL+LXJZTqMZa0FW8S6Rd0E2+4gLxoZKSyy1NTJrUGscdifOpUSeu9zzWlM85tdngjwZPqHJoklo30EZWMkCDU9/yQc2DonRwiwRmZge1c8u5WDHqzkoefAD/SF5JIPh/cyTJpdFCTNPixCoqvS443EFpsuEamuyUawy0i2HIxr1/2yijCy3eUBpawt8cYqJLwE+YEB48LAU2um6zajM7eBYoJLlKZ1mX2+FD94yw+Xf9XQ5VCyVFLQutZ5ynjsZCBoubEDfgPI+k/WlPtLeSfeQxwHl8OzgY4FXJhTwHKdrA1cimXK0n33ztAqDASrVV8nNy+qqqZgqWV76pXTY0P0AKipIHCYCDvev8YyUe4Xv7AwXfJaId2cRD1tO63XERMH1Q3fy++ya2Hcpp9fqT8OeQaEV6NKvhJlUl+/iye6v8RZx5fibvqE/hZyqiuhDS+6h82apU0MzL0Bg/J1xO5VkHJ6jO1oPqK6JB0y7zSaiJNDweaLmA/c7U7Mo+DUDf3BZ0h+DUDRLfAWWZNG/bi515VvWAWw8yKKtU="
    - secure: "U3Gqquhn5um+MOjbOS10z6+46zbeqAXn0DJ7uIY83GunsQlnyzyF0FNuX52LMPp4nn61o7hzw6tD8SLKOvaG/GqFV2zkocexa48UqU4DhrJ5Ph3jkuolPGcm8IjqOk0OikagY28df1mJf+3d2+ht25vzrvdeSggIdToEpjLU/HHvBzZ6YwQz5fnt8XD8LpbEQNdp9qvdt+6076vNIVhrDjCE9mjcvKavQhyPXQucFuEuFL0RyGgvZvnoufbDp3C2F9EO/YrzWwLcnjVFq+UqqN/XhwOqCRRHLs1XGKaHb5MBfjwi+mlIOGfdozmJZWZGQfNqvFYOwRXD6ZlNYJx5YNWAVa+MLiAx/lJ7DH6dLAPI08SqQPjpaTn7ebBoFuM+lSGCg6v/GfDNzDHnS9gsxnmk7FKK1RnOtdUDv09yH38RKZGcPEyU/GCvQMh1IjPj3myT4OzpazqoYUpW+jHNKUo/Kh4Bqbu8+XFoKRzGmQMM7C1dBxvh8WRxPIaAnj0kkKIe4532yu1rBcJs4rwpz+WQ6XEZ5E6MblU6HKzI/R/wRZ+fTYWi29VEdlBmxeZnWXUFEeqlPsvErFC0IlQJj2fidp1gunYW1m7v5MjlbC7LO6mKNxXROxuzD8+6+iFbBLtCimigG14wp+U/OXVAHapkPcOtFH5EuPgCUeZIUtM="
